name: CI
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run composer
        uses: php-actions/composer@v5

      - name: Pushing artifact to deployment server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./"
          target: "~/staging"
          rm: true

      - name: Deploying on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            echo "Stashing configuration files..."
            sudo mv /var/www/badger.atlantaned.space/badger/config.php /var/www/badger.atlantaned.space/config.php
            echo "Copying files from staging..."
            sudo rsync -aqz --delete ~/staging/ /var/www/badger.atlantaned.space/badger/
            sudo rm -rf /var/www/badger.atlantaned.space/public/*
            echo "Moving newer assets into public directory..."
            sudo mv /var/www/badger.atlantaned.space/badger/public/* /var/www/badger.atlantaned.space/public/
            sudo mv /var/www/badger.atlantaned.space/config.php /var/www/badger.atlantaned.space/badger/config.php
            echo "Updating index script location..."
            sudo sed -i 's/__DIR__.\"\/..\//__DIR__.\"\/..\/badger\//' /var/www/badger.atlantaned.space/public/index.php
            sudo sed -i 's/__DIR__.\"\/..\//__DIR__.\"\/..\/badger\//' /var/www/badger.atlantaned.space/public/icons.php
            sudo sed -i 's/__DIR__.\"\/..\//__DIR__.\"\/..\/badger\//' /var/www/badger.atlantaned.space/public/json_merge.php
            echo "Restoring file ownership..."
            sudo chown -R www-data:www-data /var/www/badger.atlantaned.space
            echo "Done!"