permissions: write-all
name: CI
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run composer
        uses: php-actions/composer@v5

      - name: Pushing artifact to deployment server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./"
          target: "~/staging"
          rm: true

      - name: Deploying on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            echo "Stashing configuration files..."
             mv /serv/www/${{ secrets.DOMAIN }}/config.php /serv/www/${{ secrets.DOMAIN }}/stg/config.php
            echo "Stashing generated icons..."
             mv /serv/www/${{ secrets.DOMAIN }}/public/icons /serv/www/${{ secrets.DOMAIN }}/stg/icons
            echo "Copying files from staging..."
             rsync -aqz --delete ~/staging/ /serv/www/${{ secrets.DOMAIN }}/
             rm -rf /serv/www/${{ secrets.DOMAIN }}/public/*
            echo "Moving newer assets into public directory..."
             mv /serv/www/${{ secrets.DOMAIN }}/public/* /serv/www/${{ secrets.DOMAIN }}/public/
             mv /serv/www/${{ secrets.DOMAIN }}/stg/config.php /serv/www/${{ secrets.DOMAIN }}/config.php
            echo "Restoring generated icons..."
             mv /serv/www/${{ secrets.DOMAIN }}/stg/icons /serv/www/${{ secrets.DOMAIN }}/public/
            echo "Restoring file ownership..."
            echo "Done!"